title: Twilio Cookbook
email: roger@freekrai.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
name: Twilio Cookbook
description: 'The Book Of Twilio, now in its second edition!'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twiliocookbook.com/" # the base hostname & protocol for your site
twitter_username: freekrai
github_username:  freekrai

paginate:         5

# Build settings
markdown: kramdown
